sudo            : false
language        : ruby
rvm             :
  - 2.4
addons          :
  apt:
    packages:
      - lftp
before_script   : chmod +x _deploy/deploy.sh
script          : ./_deploy/deploy.sh