title       : BITS SL - Balearic Islands Touristic Services
url         :
  production    : https://bitsmallorca.com
  #development   : https://test.bitsmallorca.com
  development   : https://bitsmallorca.onlinein123.com
author      : 
  name  : OnlineIn123
  url   : https://onlinein123.com

markdown        : kramdown
kramdown        :
  input : GFM
highlighter     : rouge

collections :
  pages :
    output      : true
    permalink   : /:name/

include :
  - .htaccess

exclude :
  - .asset-cache
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

gems :
  - jekyll-assets
  - autoprefixer-rails
  - uglifier
  - font-awesome-sass

assets : 
  sources       : [_assets, _assets/node_modules/slick-carousel/slick]
  precompile    : []
  destination   : /assets
  digest        : true
  source_maps   : false
  compression   : true
  gzip          : false
  defaults      :
    js      : { integrity: true }
    css     : { integrity: true }
    img     : { integrity: true }
  caching       :
    path    : ".jekyll-cache/assets"
    type    : file
    enabled : true
  plugins       :
    css     : { autoprefixer: {}}